### ISSUE TITLE
Performance tradeoffs

### ISSUE THREAD

**Issue by sftse** [mikemahoney218/lrtc#3]
In #2 I opted to split the classification into separate training and eval stages, the previous batch mode is still easily to do with this api, while interactive, single queries are not possible due to the overhead. This also makes it easier to experiment with different indexing approaches, see below.

I moved the parallelization strategy to the caller, as either async or threadpools could be used. In batch mode the parallelization in the caller seems to saturate all cores evenly even without the internal parallelism. The only reason I can think for this not being the case is if texts have vastly different sizes, although if a single text is GBs there's likely something wrong somewhere anyway.

I tried to cache the computation of the dictionary when compressing the files of the training set to reuse at eval time, I suspected it may be possible to save up to half the time of eval if the dictionary for x is known when x || y is compressed, but this resulted in a large slowdown.

Lastly, perhaps different search indexes can cut search from bruteforce `N` down to `log N` (kd-trees, metric trees...) or even constant (HNSW).

**Comment by mikemahoney218** [comment]
I'm going to close this and encourage you to fork the repo if this solves a problem for you; this is a huge change to a one-off experimental project and realistically I'm not going to find the time to dig into it in the near future.
